source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/Wwxd-Sun/ModuleSpece.git'   # 私有库
use_frameworks!

target 'LoginMoudle_Example' do
  pod 'LoginMoudle', :path => '../'
  pod 'IQKeyboardManagerSwift', '~>6.5.6'

end
